### ISSUE TITLE
Stable Release

### ISSUE THREAD

**Issue by fedemotta** [c006/yii2-migration-utility#10]
Hi,
Thank you for this extension!

Are you planning to release a stable version soon?

**Comment by c006** [comment]
Hi Federico.

I keep all my plugins in dev mode.
For me dev-master is the most up to date.
I create versions after major changes so any can use those if they like.

Let me know if you find any bugs.

Thank you,
Jon

**Comment by fedemotta** [comment]
Hi Jon,
You should use releases. Read this [github post](https://github.com/blog/1547-release-your-software).

It recommends to use [semantic versioning](http://semver.org/) which already have specified a tag for plugins in dev mode (like 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-beta, 1.0.0-beta.1, 1.0.0-rc, 1.0.0-rc.1). When your app is stable you can create a 1.0.0 release.

I can't use any project without a specific version. I have many different dependencies (all with a specific version). I think this is the best practice to avoid unwanted problems, like breaking the app after a composer update.

Cheers

**Comment by c006** [comment]
Thank you for this, I will work on converting over.

Jon

**Comment by fedemotta** [comment]
Thank you for the release! Very helpful extension!

**Comment by c006** [comment]
Great, thank you!
