### ISSUE TITLE
Some JQuery functionalities not working

### ISSUE THREAD

**Issue by fedemotta** [c006/yii2-migration-utility#11]
Hi,
There is a JQuery error:
```
backend.local/:368 Uncaught ReferenceError: jQuery is not defined
```
I think this is happening because the hardcoded js code in the view.

Thanks

**Comment by c006** [comment]
This will get it working.

File Path:
/vendor/yiisoft/yii2/web/JqueryAsset.php

<pre>
class JqueryAsset extends AssetBundle
{
    public $sourcePath = '@bower/jquery/dist';
    public $js = [
        'jquery.js',
    ];

    public $jsOptions = [
        'position' => View::POS_HEAD,
    ];
}
</pre>

**Comment by fedemotta** [comment]
Hi Jon,
I submitted a pull request with a refactor which fixes this issue. I tested those changes and it seemed to be working.

Cheers

**Comment by c006** [comment]
Thank you, that is a good idea to have jQuery load automatically.

Jon

**Comment by lostsnow** [comment]
Why change the yii framework code to fix this issue? This will causes not compatible in future.
