### ISSUE TITLE
Missing 2 Classes on a commit cause fatal error and exception!

### ISSUE THREAD

**Issue by mehrna** [c006/yii2-migration-utility#15]
Refer to this [pull request](https://github.com/c006/yii2-migration-utility/pull/14), there are 2 missing classes in default controller from this [commit](https://github.com/c006/yii2-migration-utility/commit/1cbbb1c453fe7403fdbb1866704c1c046be30234#diff-32d5fbe8a1ba37c0346f8aec2882d6fdL8)!

**Comment by c006** [comment]
Thank you for the notification.
I have added a patch. Version 1.1.2

Regards,
Jon
