### ISSUE TITLE
Tool doesn't set default value for integer if it is 0

### ISSUE THREAD

**Issue by igronus** [c006/yii2-migration-utility#22]
I have many tables with integer fields, for example:
- sum (int 11),
- datetime (int 14, fulled by triggers),
- deleted (boolean) and other on/off attributes.

All default values in these fileds are set to 0 in DB. 

However after migration generation I get such result:
```
'sum' => 'INT(14) NOT NULL',
'datetime' => 'INT(14) NOT NULL',
'deleted' => 'TYNTINT(1) NOT NULL',
```

It's wrong. Many of insertings to DB don't work after applying such migration.

To fix it it must be like:
```
'sum' => 'INT(14) NOT NULL DEFAULT 0',
'datetime' => 'INT(14) NOT NULL DEFAULT 0',
'deleted' => 'TYNTINT(1) NOT NULL DEFAULT 0',
```

However if default field value differs from 0, all is generating correctly:
```
'key' => 'INT(11) NOT NULL DEFAULT \'1\'',
```

Please fix it.

**Comment by c006** [comment]
It has been updated.

Regards
