### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by omer-sds** [c006/yii2-migration-utility#26]
is it only me or the demo link is actually not responding [http://demo.c006.us/](http://demo.c006.us/) , i get the following

> The connection has timed out
> 
> The server at demo.c006.us is taking too long to respond.
> 
>     The site could be temporarily unavailable or too busy. Try again in a few moments.
>     If you are unable to load any pages, check your computer’s network connection.
>     If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.
> 
> 

i do not have any firewall installed.

**Comment by c006** [comment]
Hi Oman.

It's down for now.
Thanks for the reminder, I need to remove the links.

Jon

**Comment by omer-sds** [comment]
cool

**Comment by c006** [comment]
Added a screen capture
